services:
  app:
    container_name: my_node_app
    image: node:18-alpine
    ports:
      - 80:3000  
    environment:
      MYSQL_HOST: mysql
      MYSQL_USER: root
      MYSQL_PASSWORD: secret
      MYSQL_DB: todos
    networks:
      - todo-app  # Connect to the same network as MySQL

networks:
  mynetwork: